// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrdyffwjlylgxfbxbztf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyZHlmZndqbHlsZ3hmYnhienRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MjM2NzUsImV4cCI6MjA3MTk5OTY3NX0.3YwCWx2Q0hLjkTPwRQsHCcVGe5B5uuT5FKUfAH2KXUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});